/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fabianbg.ten_pin_bowling;

import com.fabianbg.ten_pin_bowling.application.cotroller.CMDControllerImpl;
import com.fabianbg.ten_pin_bowling.application.cotroller.IAppController;
import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {

    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new IoC());
        IAppController app = injector.getInstance(CMDControllerImpl.class);
        app.init(args);
    }
}
